language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script:
  - asdf plugin-add fluxctl ./
  - asdf list-all fluxctl
  - asdf plugin-test fluxctl ./ 'fluxctl version' --asdf-tool-version 1.12.0
os:
  - linux
  - osx
